docs/src/gs/create-workload-cluster.md, docs/src/gs/install-cluster-api.md
=> Fix template URLs

docs/src/gs/install-cluster-api.md
Fix CRD name or OCI Cluster
Fixes #
=> Fix CRD name or OCI Cluster

docs/src/gs/networking.md, docs/src/gs/overview.md, docs/src/gs/provision-mgmt-cluster.md, docs/src/gs/pvc-fss.md, docs/src/introduction.md, docs/src/reference/glossary.md
Makes simple fixes to some spelling mistakes 
**Which issue(s) this PR fixes**:
Fixes #17
=> docs: correct spelling mistakes

docs/src/gs/create-workload-cluster.md
Clarifes the use of cluster templates.
Fixes #25
=> docs: Clarified docs for creating new clusters when using templates.

docs/src/gs/install-csi.md, docs/src/gs/install-oci-ccm.md
Add steps to install CCM/CSI usin instance principal as it is more secure.
Fixes #27
=> Add steps to install CCM/CSI using instance principal

config/default/manager_image_patch.yaml
=> Fix image path

Makefile, docs/build.sh
This should help simplify downloading mdbook and serving the book
locally.
No open issue currently related to this PR
=> feat: Add support for mdbook

docs/src/SUMMARY.md, docs/src/networking/private-cluster.md, templates/cluster-template-local-vcn-peering.yaml, templates/cluster-template-remote-vcn-peering.yaml
Add documentation for Private Clusters and VCN peering
Fixes #63 , Fixes #16
=> Add documentation for private clusters and VCN peering

api/v1beta1/ocimachinetemplate_webhook.go, api/v1beta1/ocimachinetemplate_webhook_test.go, api/v1beta1/validator.go, templates/clusterclass-example.yaml, test/e2e/data/infrastructure-oci/v1beta1/cluster-template-cluster-class/clusterclass-test-cluster-class.yaml
Adding more validation to the `OCIMachineTemplate` webhook
Fixes #71
=> feat: update OCIMachineTemplate webhook validations

README.md
The readme should contain the information for our office hours and community engagement info
No open related issue
=> docs: Update README with community and office hours info

templates/cluster-template-oci-addons.yaml, test/e2e/data/ccm/ccm.yaml
Bumps the version for OCIs cloud controller manager (CCM) for our template and tests
No open issue
=> Update OCI's cloud controller manager image version

.github/workflows/build-cluster-api-provider-book.yaml, docs/src/gs/create-workload-cluster.md, docs/src/gs/install-cluster-api.md, metadata.yaml
Bump CAPOCI to next version and use the latest version of mdBook
Fixes #
=> Bump CAPOCI version and mdBook version

api/v1beta1/ocimachine_types.go
Just a quick cleanup of a comment
Fixes #
=> docs: cleanup MachineFinalizer comment

docs/book.toml, docs/build.sh, docs/mdbook-admonish.css
This fixes breaking changes after upgrading to the newer version of mdbook. This changes was made in the [release-v0.3.0 branch](https://github.com/oracle/cluster-api-provider-oci/commit/2aa8edce6d6b4739e83fb56469a4217e0e948ffe)
no open issues
=> Update mdbook version which updates mdbook-admonish requirements

Tiltfile
simple version bumps for dev environment
No open issues for this
=> feat: update capi and kube version in Tiltile

.github/workflows/build-cluster-api-provider-book.yaml, docs/book.toml, docs/build.sh, docs/mdbook-admonish.css, metadata.yaml
Update mdbook version and version and metadata
Fixes #
=> Update mdbook version and version and metadata

docs/src/SUMMARY.md, docs/src/gs/externally-managed-cluster-infrastructure.md, docs/src/networking/custom-networking.md
Added a callout and link to more documentation with more networking
examples to better help users locate the more in-depth docs.
Fixes #121
=> Update externally-managed-infrastructure docs

docs/src/SUMMARY.md, docs/src/gs/externally-managed-cluster-infrastructure.md, docs/src/networking/custom-networking.md
Cherry picking from `release-v0.4.0`
> Added a callout and link to more documentation with more networking examples to better help users locate the more in-depth docs.
=> Update externally-managed-infrastructure docs (#122)

docs/src/gs/install-csi.md
Fixes two bugs in the documentation.
Fixes #124, Fixes #125
=> docs: update install-csi.md doc

docs/src/gs/install-csi.md
This is a cherry pick from PR #128 
> Fixes two bugs in the documentation.
No open issue.
=> docs: update install-csi.md doc (#128)

docs/src/gs/customize-worker-node.md
Add doc for burstable instances
Fixes #
=> Add doc for burstable instances

README.md
Quick update to keep the CAPI version matrix up-to-date
No open issue for this.
=> docs: Update CAPI support matrix

docs/src/SUMMARY.md, docs/src/gs/create-gpu-workload-cluster.md
This details how to launch a VM or BM GPU cluster using the Nvidia GPU-Operator
Fixes #159
=> docs: Add how to create gpu workload cluster docs

docs/src/gs/install-oci-ccm.md
This should help answer how to modify the CCM example file.
No open issues
=> doc: update install-oci-ccm.md

docs/src/SUMMARY.md, docs/src/gs/create-mhc-workload-cluster.md, templates/cluster-template-healthcheck.yaml
Add an example cluster template to show how to setup `MachineHealthChecks`. 
Fixes #144
=> feat: Add MachineHealthCheck example template

metadata.yaml
Now that v0.6.0 is released and the branch cut this gets the v0.7.0 version ready for next release
No open issues for this.
=> Update release references to next version

test/e2e/config/e2e_conf.yaml
update tests to latest CAPI version
No open issues
=> Update e2e cluster-api version

README.md, SECURITY.md
Simple update to keep in line with
https://github.com/oracle/template-repo
No open issue
=> docs: Update README and Security docs

README.md
Keeping `README.md` in sync with https://github.com/oracle/template-repo
no open issue
=> docs: add `Contriubting` section to README.md

docs/proposals/20230117-cluster-level-identity.md
Proposal for Cluster identity
Fixes #
=> Proposal for Cluster identity

docs/src/gs/create-workload-cluster.md
Just a simple link update to use the `latest` tag instead of a hard coded version.
No open issues
=> docs: Update create-workload-cluster.md

metadata.yaml
Fix metadata file to next release
Fixes #
=> Fix metadata file to next release

cloud/scope/managed_machine_pool.go, cloud/scope/managed_machine_pool_test.go, cloud/services/containerengine/client.go, cloud/services/containerengine/mock_containerengine/client_mock.go, docs/src/managed/managedcluster.md, exp/api/v1beta1/ocimanagedmachinepool_webhook.go, exp/api/v1beta1/ocimanagedmachinepool_webhook_test.go, templates/cluster-template-managed-flannel.yaml, templates/cluster-template-managed-private.yaml, templates/cluster-template-managed.yaml, test/e2e/config/e2e_conf.yaml, test/e2e/data/infrastructure-oci/v1beta1/cluster-template-managed/machine-pool.yaml, test/e2e/data/shared/v1beta1/metadata.yaml
Add support for lookup of nodepool image if not present
Fixes #146
=> Add support for lookup of nodepool image if not present

docs/src/gs/install-cluster-api.md
This is a quick update to make sure our book has the latest version
No open issues.
=> docs: Update install-cluster-api.md with new version

metadata.yaml
=> Update metadata file to next release

api/v1beta1/conversion.go, api/v1beta1/ocicluster_conversion.go, cloud/config/config.go, cloud/scope/clients_mock.go, cloud/scope/machine.go, cloud/scope/machine_pool.go
Fix implicit aliasing and other errors and other gosec errors
Fixes #
=> Fix implicit aliasing and other errors

go.mod, go.sum, templates/cluster-template-alternative-region.yaml, templates/cluster-template-antrea.yaml, templates/cluster-template-arm-free-tier.yaml, templates/cluster-template-failure-domain-spread.yaml, templates/cluster-template-healthcheck.yaml, templates/cluster-template-local-vcn-peering.yaml, templates/cluster-template-machinepool.yaml, templates/cluster-template-oci-addons.yaml, templates/cluster-template-oraclelinux.yaml, templates/cluster-template-remote-vcn-peering.yaml, templates/cluster-template-windows-calico.yaml, templates/cluster-template.yaml, test/e2e/data/infrastructure-oci/v1beta1/bases/md.yaml, test/e2e/data/infrastructure-oci/v1beta2/bases/md.yaml, test/e2e/data/infrastructure-oci/v1beta2/cluster-template-machine-pool/machine-pool.yaml, test/e2e/data/infrastructure-oci/v1beta2/cluster-template-multiple-node-nsg/md.yaml, test/e2e/data/infrastructure-oci/v1beta2/cluster-template-oracle-linux/md.yaml, test/e2e/data/infrastructure-oci/v1beta2/cluster-template-windows-calico/md.yaml
Update KubeadmConfigTemplate version and CAPI version
Fixes #279
=> Update KubeadmConfigTemplate version and CAPI version

README.md
=> docs: update readme zoom link

docs/src/SUMMARY.md, docs/src/reference/api-reference.md
Remove references to local API reference docs. The local reference docs needs a little more work in release workflow before it can work.
Fixes #
=> Remove references to local API reference docs

metadata.yaml
Bumps the version to the next release on main
Fixes #
=> Update metadata to next release

README.md, docs/src/introduction.md, metadata.yaml
Increment metadata version
Fixes #
=> Increment metadata version

cloud/scope/load_balancer_reconciler.go, cloud/scope/load_balancer_reconciler_test.go, cloud/scope/machine.go, cloud/scope/machine_test.go, cloud/scope/network_load_balancer_reconciler.go, cloud/scope/network_load_balancer_reconciler_test.go
Backport of #330 to release v0.11.0
Fixes #
=> Retry on delete backend failure (#330)

docs/src/gs/install-cluster-api.md
Fix docs for instance principal
Fixes #
=> Fix docs for instance principal

config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml
This change to the CRDs was left out of the previous feature add.
Fixes #
=> bug: Update the CRDs for the workrequest feature

cloud/scope/native_pod_network_reconciler.go
We need to add ipfamilies parameter as well to align with OCI
Fixes #NA
=> Fix: Add IPFamilies support for NPN CR

exp/api/v1beta2/ocimanagedmachinepool_webhook.go
**Which issue(s) this PR fixes** :
Fixes #426
=> validateUpdate returns warning on k8s version change

cloud/scope/util.go
Check for nsg.ID dereference.
**Which issue(s) this PR fixes** :
Fixes #435
=> bug: Check if nsg.ID is null

cloud/scope/load_balancer_reconciler.go, cloud/scope/machine.go, cloud/scope/machine_pool.go, cloud/scope/managed_control_plane.go, cloud/scope/managed_machine_pool.go, cloud/scope/network_load_balancer_reconciler.go, cloud/scope/nsg_reconciler.go, cloud/scope/route_table_reconciler.go, cloud/scope/security_list_reconciler.go, cloud/scope/subnet_reconciler.go, cloud/scope/util.go, cloud/scope/virtual_machine_pool.go, exp/api/v1beta2/ocimanagedmachinepool_webhook.go
Adding more checks for pointer dereference.
Which issue(s) this PR fixes :
=> Pointer check
