docs/src/introduction.md

The getting started Installation links were 404ing (wrong path) 
and the main cluster_api link was pointing to the wrong repo
**Which issue(s) this PR fixes**:
Fixes #8

fix: update introduction document links to clear up 404s

---

.gitignore
Makefile
test/e2e/cluster_test.go
test/e2e/config/e2e_conf.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-bare-metal/cluster.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-bare-metal/kustomization.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-bare-metal/md.yaml

Add support to bare metal tests, but also making sure our default e2e testing strategy doesn't run them by default.
**Which issue(s) this PR fixes**:
Currently no open issues.

test: add bare metal support for e2e tests

---

.github/ISSUE_TEMPLATE/enhancement.md

The `feature` label never existed. The correct label is `enhancement`
No open issue for this change.

fix: Update enhancement labels

---

docs/build.sh
docs/src/gs/create-workload-cluster.md
templates/cluster-template-alternative-region.yaml

Add a section that documents how to use the new
`cluster-template-alternative-region.yaml` template to show users
how to launch clusters in multiple regions.
Fixes #46

docs: update workload cluster with multi-region support

---

docs/src/gs/create-workload-cluster.md
docs/src/gs/install-cluster-api.md
metadata.yaml

To help make sure we don't forget to do this (until things are automated)
I wanted to bump the version for our next release now that v0.2.0 has
been cut.
No open issues for this at this time.

docs: bump CAPOCI version to next release

---

Makefile
api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
controllers/ocicluster_controller.go
controllers/ocicluster_controller_test.go
docs/src/networking/custom-networking.md
test/e2e/cluster_test.go
test/e2e/config/e2e_conf.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-cluster-class/clusterclass-test-cluster-class.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-externally-managed-vcn/cluster.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-externally-managed-vcn/kustomization.yaml

Support use case where VCN can be managed externally but API Server LB can be managed by CAPOCI.
Fixes #64

Add support for externally managed VCN

---

api/v1beta1/ocicluster_types.go
api/v1beta1/ocicluster_webhook.go
api/v1beta1/ocicluster_webhook_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
templates/clusterclass-example.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-cluster-class/clusterclass-test-cluster-class.yaml

`CompartmentId` is still mandatory, but the admission webhook is now handling the validation.
Fixes #66

feat: remove CompartmentId mandatory from ocicluster_types

---

api/v1beta1/ocicluster_webhook.go
api/v1beta1/ocicluster_webhook_test.go
api/v1beta1/types.go
api/v1beta1/validator.go
cloud/ociutil/ociutil.go

This expands on the OCICluster webhook adding some more validation during cluster creation.
Fixes #70

feat: update OCICluster webhook validations

---

 OWNERS 
OWNERS_ALIASES
RELEASE.md
SECURITY.md
SECURITY_CONTACTS
code-of-conduct.md

As part of https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories
we need to make sure our project contains template files as per the
https://github.com/kubernetes/kubernetes-template-project
No currently opened issue

docs: Add kubernetes-template files before donating to kubernetes-sigs

---

api/v1beta1/ocicluster_webhook_test.go
api/v1beta1/validator.go
cloud/scope/subnet_reconciler.go
cloud/scope/subnet_reconciler_test.go
test/README.md
test/e2e/e2e_suite_test.go

The PR adds the following
- Doc to supports instance principal based e2e testing
- Minor changes for instance principal based e2e testing
- Fix the empty subnet name and CIDR bug, CAPOCI should allow empty values
Fixes #83 , Fixes #47

Add doc for instance principal based e2e and fix empty subnet cidr bug

---

Makefile
cloud/scope/machine_pool.go
test/e2e/cluster_test.go
test/e2e/config/e2e_conf.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-machine-pool/kustomization.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-machine-pool/machine-pool.yaml

Initial set of e2e for machinepool
Fixes #91 except for instance config upgrade for which new issue will be opened

Simple test for machinepool

---

cloud/scope/machine_pool.go

Since it is possible for a MachinePool to be quite large we need to
make sure we iterate through all pages of possible machine pool
instances.
We have another ticket to make sure all other list calls are also
paginated.
Fixes #99

feat: add pagination to MachinePool list api calls

---

templates/cluster-template-oci-addons.yaml
test/e2e/data/ccm/ccm.yaml

Version 1.23.0 of CCM was just released. We need to stay up-to-date
https://github.com/oracle/oci-cloud-controller-manager/releases/tag/v1.23.0
Fixes #106

test: Update the `cloud-provider-oci` image for e2e tests

---

cloud/scope/cluster.go
cloud/scope/drg_reconciler.go
cloud/scope/drg_reconciler_test.go
cloud/scope/drg_rpc_attachment_reconciler.go
cloud/scope/drg_vcn_attachment_reconciler.go
cloud/scope/drg_vcn_attachment_reconciler_test.go
cloud/scope/internet_gateway_reconciler.go
cloud/scope/internet_gateway_reconciler_test.go
cloud/scope/load_balancer_reconciler.go
cloud/scope/load_balancer_reconciler_test.go
cloud/scope/nat_gateway_reconciler.go
cloud/scope/nat_gateway_reconciler_test.go
cloud/scope/nsg_reconciler.go
cloud/scope/nsg_reconciler_test.go
cloud/scope/route_table_reconciler.go
cloud/scope/route_table_reconciler_test.go
cloud/scope/security_list_reconciler.go
cloud/scope/service_gateway_reconciler.go
cloud/scope/service_gateway_reconciler_test.go
cloud/scope/subnet_reconciler.go
cloud/scope/subnet_reconciler_test.go
cloud/scope/vcn_reconciler.go
cloud/scope/vcn_reconciler_test.go

Ignore sending freeform and defined tags during update of resources
Fixes #130

Tags should not be sent in update API calls

---

Dockerfile
cloud/scope/clients.go
hack/version.sh
main.go
version/version.go

This allows us to use build version information to help debug
issues.
No open issue

feat: Add version information

---

docs/src/gs/install-cluster-api.md
metadata.yaml

Update release references to next version
Fixes #

Update release references to next version

---

OWNERS
OWNERS_ALIASES 

The OWNERS file is needed to setup this repo with the [community](https://github.com/kubernetes/community) sig list for office hours.
No open issue

doc: Add simple OWNERS file

---

api/v1beta1/ocicluster_webhook.go
api/v1beta1/ocicluster_webhook_test.go

This will now check the cluster name before trying to create. We had some issues where the cluster would fail to come up due to networking issues if the cluster had a `.` in the name.
Fixes #142

feat: Add cluster name check for ocicluster webhook

---

controllers/ocicluster_controller.go
controllers/ocimachine_controller.go
exp/controllers/ocimanagedcluster_controller.go
exp/controllers/ocimanagedcluster_controlplane_controller.go
main.go

This sets up default parameters and allows users to modify the number of concurrent reconcilers for the `OCIClusterReconciler`, `OCIMachineReconciler`, `OCIMachinePoolReconciler`, `OCIManagedMachinePoolReconciler`, `OCIManagedClusterReconciler` and the `OCIManagedClusterControlPlaneReconciler`.
Fixes #149

feat: add support for `MaxConcurrentReconciles` for reconcilers

---

Tiltfile
templates/cluster-template-oci-addons.yaml
test/e2e/config/e2e_conf.yaml
test/e2e/data/ccm/ccm.yaml
test/e2e/data/infrastructure-oci/v1beta1/bases/ccm.yaml

make 1.24 default version in test.
Fixes #139

feat: update e2e test version and ccm version

---

cloud/scope/managed_control_plane.go
cloud/scope/managed_machine_pool.go
cloud/scope/managed_machine_pool_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepools.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepooltemplates.yaml
exp/api/v1beta1/ocimanagedmachinepool_types.go
exp/api/v1beta1/zz_generated.deepcopy.go
exp/controllers/ocimanaged_machinepool_controller_test.go
templates/cluster-template-managed-private.yaml
templates/cluster-template-managed.yaml

Add kubernetes version to ocimanagedmachinepool spec. Also fix an issue where there was an unwanted node pool upgrade.
Fixes #162

Add kubernetes version in OKE node pool spec

---

api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
docs/src/SUMMARY.md
docs/src/gs/customize-worker-node.md

Add documentation for customising worker nodes and fix misc bugs
Fixes #

Add documentation for worker node customization

---

.gitignore

after running `make generate-e2e-templates` I notice two templates weren't ignored like our other ones.
No open issues for this.

test: ignore more e2e templates

---

templates/cluster-template-oci-addons.yaml

Fix OCI Addons template for Kubernetes 1.24
Fixes #198

Fix OCI Addons template for Kubernetes 1.24

---

cloud/scope/managed_machine_pool.go
cloud/scope/managed_machine_pool_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepools.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepooltemplates.yaml
exp/api/v1beta1/ocimanagedmachinepool_types.go
templates/cluster-template-managed-private.yaml
templates/cluster-template-managed.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-managed/machine-pool.yaml

Use externally managed replicas annotation and remove the CAPOCI specific flag which was introduced
Fixes #201

Use externally managed replicas annotation and remove the CAPOCI specific flag which was introduced

---

test/e2e/config/e2e_conf.yaml

bumped to [1.3.0 release](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.0) 
no open issue

Update the CAPI version in the e2e_conf.yaml

---

test/e2e/conformance_test.go

Update to use gomega gmeasure
Fixes #189

Update to use gomega gmeasure

---

exp/api/v1beta1/constants.go
templates/cluster-template-managed-private.yaml

Fix private managed template to have correct seclist and Subnet CIDR
Adding all required Seclist in NSG so that customers can use them as a template when they want to customize
Fixes #

Fix private managed template to have correct seclist and Subnect CIDR

---

Makefile
docs/src/SUMMARY.md
docs/src/gs/create-windows-workload-cluster.md
scripts/ci-e2e.sh
templates/cluster-template-windows-calico.yaml
test/e2e/cluster_test.go
test/e2e/config/e2e_conf.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-windows-calico/kustomization.yaml
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-windows-calico/md.yaml

Windows image builds are now supported using [Image-Builder v0.1.14](https://github.com/kubernetes-sigs/image-builder/releases/tag/v0.1.14). This adds Windows documentation and templates.
Fixes #206

feat: Add windows support

---

Tiltfile

We create the `process.txt` file since the `config/manager/manager.yaml` changed some permissions. If the `process.txt` file exists the permissions issues go away.
Fixes #240

Fix: Tiltfile with process.txt issue

---

api/v1beta1/zz_generated.deepcopy.go
cloud/scope/load_balancer_reconciler.go
cloud/scope/machine.go
main.go

Add options to customize leader election
Fixes #

Add options to customize leader election

---

cloud/scope/load_balancer_reconciler.go
cloud/scope/load_balancer_reconciler_test.go
cloud/scope/network_load_balancer_reconciler.go
cloud/scope/network_load_balancer_reconciler_test.go

Fix LB reconciliation to support multiple NSG
Fixes #259

Fix LB reconciliation to support multiple NSG

---

docs/src/gs/advanced.md
docs/src/gs/create-mhc-workload-cluster.md

Making the MHC a bit more clear which steps to run on specific clusters. This should help make it a bit more clear for users.
Adding the setup heterogeneous cluster section to advanced. This should allow users to see how to setup a mix workload windows/linux cluster.
Fixes #265

Update the machineHealthCheck and advance docs

---

api/v1beta1/doc.go
api/v1beta1/groupversion_info.go
api/v1beta2/doc.go
api/v1beta2/groupversion_info.go
docs/build.sh
docs/src/SUMMARY.md
docs/src/reference/api-reference.md
docs/src/reference/v1beta1-api.md
docs/src/reference/v1beta1-exp-api.md
docs/src/reference/v1beta2-api.md
docs/src/reference/v1beta2-exp-api.md
exp/api/v1beta1/doc.go
exp/api/v1beta2/doc.go

If crds.dev goes away we have the APIs being generated in our book as well.
Fixes #269

docs: Add generated API references to our book

---

cloud/scope/machine.go
cloud/scope/machine_test.go

Handle nil pointer in Lb backend delete. This happens when instance was created, but was not added to backend because the instance does not have IP address. Then when instance is deleted, we get the following stack trace.
```
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 553 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1dd91a0, 0xc0001c0b10})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/oracle/cluster-api-provider-oci/cloud/scope.(*MachineScope).IP(...) …
```

Handle nil pointer in Lb delete

---

docs/src/gs/iam/iam-oke.md

Fix OKE policy in doc
Fixes #273

Fix OKE policy in doc

---

docs/src/networking/custom-networking.md

Add docs for LBaaS support
Fixes #237

Add docs for LBaaS support

---

docs/src/SUMMARY.md
docs/src/managed/features.md

Add doc for OKE addons and node pool cycling
Fixes #288

Add doc for OKE addons and node pool cycling

---

.github/workflows/build-cluster-api-provider-book.yaml

Use 1.8.0 version of mdbook admonish to fix book publish errors - https://github.com/oracle/cluster-api-provider-oci/actions/runs/5758083686/job/15610077049
Fixes #

Use 1.8.0 version of mdbook admonish to fix book publish errors

---

api/v1beta2/ociclusteridentity_types.go
cloud/util/util.go
docs/src/gs/multi-tenancy.md
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster-identity.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/kustomization.yaml

Add InstancePrincipal support to ClusterIdentity. 
Just as an add on, some other cloud provider are also moving away from env variable based identity to use Cluster Identity. So this will help us to be on par.
Fixes #314

Add instanceprincipal clusteridentity support

---

exp/controllers/ocimachinepool_controller.go
exp/controllers/ocimanaged_machinepool_controller.go
exp/controllers/ocivirtual_machinepool_controller.go

… without exponential backoff
Fixes #317

Fix reconcilers where error condition leads to infinite reconciliation

---

cloud/util/util.go
metadata.yaml

Use generate name so that conflicts do not arise in case of multiple clusters
Fixes #

Use generate name so that conflicts do not arise in case of multiple clusters

---

api/v1beta2/ocimanagedcluster_webhook.go
api/v1beta2/types.go
cloud/scope/nsg_reconciler.go
cloud/scope/nsg_reconciler_test.go
docs/src/networking/custom-networking.md
test/e2e/cluster_test.go
test/e2e/data/infrastructure-oci/v1beta1/cluster-template-custom-networking-nsg/cluster.yaml

Add support for NSG chaining
Fixes #306

Add support for NSG chaining

---

controllers/ocimachine_controller.go
controllers/ocimachine_controller_test.go
exp/controllers/ocimachinepool_controller.go
exp/controllers/ocimanaged_machinepool_controller.go
exp/controllers/ocimanaged_machinepool_controller_test.go
exp/controllers/ocivirtual_machinepool_controller.go
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed/cluster.yaml

Fix machinepool infra cluster lookup issue
Fixes #324

Fix machinepool cluster name issue

---

SECURITY.md
cloud/scope/util.go

Backport of https://github.com/oracle/cluster-api-provider-oci/commit/3cff30b081100f5dec55765514f79d77f73168da to v0.12.0
Fixes #

Fix reconciliation comparisons when there are no NSGs

---

cloud/scope/load_balancer_reconciler.go
cloud/scope/load_balancer_reconciler_test.go
cloud/scope/machine.go
cloud/scope/machine_test.go
cloud/scope/network_load_balancer_reconciler.go
cloud/scope/network_load_balancer_reconciler_test.go

* Retry on create/delete backend failure
* Check for LB/NLB status before reconciliation. This is to make sure that CAPOCI do not proceed with machine creation if the LB creation fails.
Fixes #331 , #332

Retry on delete backend failure

---

api/v1beta2/ocimachine_types.go
controllers/ocimachine_controller.go
controllers/ocimachine_controller_test.go

Add machine delete on VM termination
Fixes #

Add machine reconcile delete on termination

---

config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedmachinepools.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocivirtualmachinepools.yaml
exp/api/v1beta1/ocimanagedmachinepool_types.go
exp/api/v1beta1/ocivirtualmachinepool_types.go
exp/api/v1beta1/zz_generated.conversion.go
exp/api/v1beta2/ocimanagedmachinepool_types.go
exp/api/v1beta2/ocivirtualmachinepool_types.go
exp/controllers/ocimanaged_machinepool_controller.go
exp/controllers/ocimanaged_machinepool_controller_test.go
exp/controllers/ocivirtual_machinepool_controller.go
exp/controllers/ocivirtual_machinepool_controller_test.go

Add node pool state in machine pool status
Fixes #

Add node pool status in machine pool status

---

cloud/scope/machine.go
cloud/scope/machine_test.go
controllers/ocimachine_controller.go
controllers/ocimachine_controller_test.go

Fix vm state bug and deletion bug
Fixes #337 , #339

Fix vm state bug and deletion bug

---

cloud/scope/machine.go
cloud/scope/network_load_balancer_reconciler.go

- This PR is "add nil check on"
- `cloud/scope/network_load_balancer_reconciler.go`
- `cloud/scope/machine.go`
- Background
- To prevent Go from crashing when using Pointer references  
Fixes #348

Fix: add nil check on Machine and Network Load Balancer

---

cloud/scope/machine.go
cloud/scope/machine_test.go

Handle machine deletion when NLB/LB has been deleted
Fixes #347

Handle machine deletion when NLB/LB has been deleted

---

cloud/scope/machine.go
metadata.yaml

Do not sent fault domain if failure domain is set as empty. OCI Compute will select the right fault domain based on various factors.
Fixes #351

Do not sent fault domain if failure domain is set as empty

---

docs/src/gs/multi-tenancy.md

Add instructions for Workload identity policies
Fixes #

Add instructions for Workload identity policies

---

api/v1beta1/types.go
api/v1beta1/zz_generated.conversion.go
api/v1beta2/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml

Add support for name in RPC
Fixes #

Add support for name in RPC

---

controllers/ocimachine_controller.go
controllers/ocimachine_controller_test.go

Set instance in moving state to be not ready, but dont throw error
Fixes #366

Set instance in moving state to be not ready, but dont throw error

---

api/v1beta1/types.go
api/v1beta1/zz_generated.conversion.go
api/v1beta1/zz_generated.deepcopy.go
api/v1beta2/types.go
api/v1beta2/zz_generated.deepcopy.go
cloud/scope/vcn_reconciler.go
cloud/scope/vcn_reconciler_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedclustertemplates.yaml
go.mod
go.sum

Add support for multiple CIDR in vcn and fix dns label bug
Fixes #368

Add support for multiple CIDR in vcn and fix dns label bug

---

test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed/machine-pool.yaml

Using KUBERNETES_VERSION instead of OCI_MANAGED_KUBERNETES_VERSION will have a version mismatch and the managed nodes will fail to join.
Fixes #
Before this the `Managed Cluster - Simple` was not passing for me. I'm not sure how it was for others. This basically makes sure the cluster and the machine pool are using the same K8s version.

fix: Machinepool should use OCI_MANAGED_KUBERNETES_VERSION ENV

---

cloud/ociutil/ociutil.go
cloud/scope/cluster.go
cloud/scope/load_balancer_reconciler.go
cloud/scope/load_balancer_reconciler_test.go
cloud/scope/machine.go
cloud/scope/machine_test.go
cloud/scope/network_load_balancer_reconciler.go
cloud/scope/network_load_balancer_reconciler_test.go
cloud/services/networkloadbalancer/client.go
cloud/services/networkloadbalancer/mock_nlb/client_mock.go
controllers/ocimachine_controller_test.go

The work-request-errors for loadbalancer and networkloadbalancer will be populated in the events incase of failure of workrequests for better information.
**Which issue(s) this PR fixes**:
Fixes #383

feat: Add work request errors in events/logs when work-request is failed for LB/NLB

---

Tiltfile
api/v1beta1/types.go
api/v1beta2/types.go
cloud/scope/machine.go
cloud/scope/machine_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
go.mod
go.sum

feat Add support for paravirtualized launch volume attachment
**What this PR does / why we need it**: 
Recently support was added for configuring [paravirtualized launch volume attachments](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/InstanceConfigurationAttachVolumeDetails) at instance creation with go sdk v65.75.1 onwards, added the support for attaching paravirtualized volume at instance creation via cluster api provider.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: #388 
Fixes #
Updated OCI Go sdk version to v65.81.1
Updated tilt-helper docker manifest go version to 1.21.8
added support for paravirtualized volumes
Signed-off-by: Mayank Kakani …

feat #388: Add support for paravirtualized launch volume attachment

---

.github/workflows/release.yaml

Fixes the release workflow issue and is now working on the release branch here: https://github.com/oracle/cluster-api-provider-oci/actions/runs/10941758099
v2 is deprecated
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Update release workflow to use new upload-artifact@v4

---

.gitignore
Makefile
api/v1beta1/types.go
api/v1beta2/ocicluster_webhook.go
api/v1beta2/types.go
cloud/scope/machine.go
cloud/scope/route_table_reconciler.go
cloud/scope/subnet_reconciler.go
cloud/scope/vcn_reconciler.go
cloud/scope/vcn_reconciler_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimachinetemplates.yaml
docs/src/SUMMARY.md
docs/src/networking/ipv6.md
hack/ensure-kubectl.sh
templates/cluster-template-with-ipv6.yaml
templates/cluster-template-with-paravirt-bv.yaml
test/e2e/cluster_test.go
test/e2e/config/e2e_conf.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-machine-with-ipv6/cluster.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-machine-with-ipv6/kustomization.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-machine-with-ipv6/md.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-with-paravirt-bv/kustomization.yaml
test/e2e/data/infrastructure-oci/v1beta2/cluster-template-with-paravirt-bv/md.yaml

This PR adds support for IPv6 at instance creation.
Adds support for IPv6 for VCN and subnets.
Adds paravirtualized block volumes templates.
Which issue(s) this PR fixes:
Fixes #400

Ipv6 implementation

---

config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanes.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanetemplates.yaml

Updates CRDs for oci managed control plane to make OIDC configuration available for v1beta2
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/oracle/cluster-api-provider-oci/issues/425

added oidc config for v1beta2

---

config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanes.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ocimanagedcontrolplanetemplates.yaml

Updates CRDs for oci managed control plane to make OIDC configuration available for v1beta2
Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/oracle/cluster-api-provider-oci/issues/425

added oidc config for v1beta2 (#427)

---

exp/api/v1beta2/ocimanagedmachinepool_webhook_test.go

This changes web hook tests so teams using custom images not tied to k8s version can upgrade node pools without being blocked by admission webhook
Which issue(s) this PR fixes:
Fixes webhook tests for https://github.com/oracle/cluster-api-provider-oci/issues/426

validateUpdate returns warning on k8s version change

---

api/v1beta1/conversion_test.go
api/v1beta1/ocicluster_conversion_test.go
api/v1beta2/ocicluster_webhook_test.go
api/v1beta2/ocimachinetemplate_webhook_test.go
api/v1beta2/ocimanagedcluster_webhook_test.go
api/v1beta2/ocimanagedcontrolplane_webhook_test.go
cloud/config/config_test.go
cloud/ociutil/ptr/from_ptr.go
cloud/ociutil/ptr/from_ptr_test.go
cloud/scope/load_balancer_reconciler.go
cloud/scope/machine.go
cloud/scope/machine_pool.go
cloud/scope/managed_control_plane.go
cloud/scope/managed_machine_pool.go
cloud/scope/network_load_balancer_reconciler.go
cloud/scope/nsg_reconciler.go
cloud/scope/security_list_reconciler.go
cloud/scope/subnet_reconciler.go
cloud/scope/util.go
cloud/scope/virtual_machine_pool.go

- adding wrappers to handle nil checks
- grow coverage regarding unit testing

Ptr wrapper and unit tests
